### ISSUE TITLE
Payments Requests containing ReadRefundAccount=Yes should return accountNo and sortcode

### ISSUE THREAD

**Issue by BohoCode** [OpenBankingToolkit/openbanking-toolkit#14]
**ZD:** 55834

When a TPP sets the ReadRefundAccount=yes in a payment request the response should contain Sort Code and Account Number.

The ReadRefundAccount field was added in 3.1.4 so this functionality needs to be put into a filter and that filter needs to be added to 3.1.4, 3.1.5 & 3.1.6 controllers.

### Acceptance Criteria
- [x] End to end test in postman covers this functionality and pass against master
- [x] Functional Tests cover this functionality and pass against master

**Comment by jsanhc** [comment]
### Payments affected
- DomesticPayment
- DomesticScheduledPayment
- DomesticStandingOrder
- InternationalPayment
- InternationalScheduledPayment
- InternationalStandingOrder

### Versions
- From **3.1.4** to latest

**Comment by jsanhc** [comment]
Related issue: [16:Payment Initiation model version 3.1.4 missed fields (Refund)](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/16)
- [x] Fixed
