### ISSUE TITLE
Accounts not displayed in consent UI

### ISSUE THREAD

**Issue by matt-wills** [OpenBankingToolkit/openbanking-toolkit#20]
Whilst testing the consent flow, it is not possible to select an account:

![image](https://user-images.githubusercontent.com/63234126/110622036-d8f3d980-8192-11eb-97f4-049b531a51da.png)

After investigating the issue, it appears that the objects within `AccountWithBalance` are not serializing the JSON in the expected format (each property should start with an uppercase letter).

**Comment by BohoCode** [comment]
Fixed. Now seen in the ob.forgerock.financial sandbox;

![image](https://user-images.githubusercontent.com/1516395/110929219-a5928580-831f-11eb-818b-9e061f745278.png)
