### ISSUE TITLE
Take ownership of spring-cloud-multi-auth

### ISSUE THREAD

**Issue by BohoCode** [OpenBankingToolkit/openbanking-toolkit#34]
As really the only major users of spring-cloud-multi-auth, and as the release mechansim of the parent openbanking4-dev repository has broken, now seems to be the right time to take ownership of this repo.

- [x] Break the fork and become independent of the parent project
- [x] Fix the poms to be com.forgerock.spring.security groupId
- [x] Change package names to be com.forgerock
- [x] Fix badges in readme
- [x] Set up CI/CD

**Comment by BohoCode** [comment]
Support issue raised to Detach the fork and turn it into a standalone repo;
https://support.github.com/ticket/personal/0/1140325

Github have now confirmed this has been done.

**Comment by jsanhc** [comment]
Fix badges in readme file.
