### ISSUE TITLE
TPP unable to create application when using a Re-Direct URI with .technology

### ISSUE THREAD

**Issue by BohoCode** [OpenBankingToolkit/openbanking-toolkit#8]
**Zendesk Issue:** https://forgerock.zendesk.com/agent/tickets/49075
**Date Raised:** 22/04/2020
**Environment:** sandbox.lloydsbanking.com

**Description of the bug by the customer**
TPP is trying to create an Application on the LBG Sandbox using the following Re-Direct URI
https://bopp.technology/api
If they shorten the domain extension to something shorter it is OK, The system does not accept `.technology`.
For example, it is OK with .com, .tech, but not OK with .technology.
The URI uploads successfully to the OBIE Sandbox.

**Investigation of the bug by the OBRI team**

Reproduced in queen-rc6 on lbg-dev.forgerock.financial

**To Reproduce**
Steps to reproduce the behaviour:

1.  Go to register.lbg-dev.forgerock.financial
2.  Sign into the OB Directory
3.  When redirected to the register.lbg-dev.forgerock.financial page, create the new application using `https://bopp.technology/api` as the redirect URI
4.  The field turns red and will not let you enter the url due to the length of the TLD (the number of characters in `technology`

**Expected behaviour**
The URL should be accepted

**Current behaviour**
The form can't be submitted with such a long TLD

### Release Notes

Affected App: X

Description: X
<end release notes>

**Comment by shprink** [comment]
Fix: https://github.com/OpenBankingToolkit/openbanking-ui-common/commit/bdd3212bf36950ac3578fdd7667b6b8a354021a3

**Comment by shprink** [comment]
PRs:
https://github.com/OpenBankingToolkit/openbanking-aspsp/pull/183
https://github.com/OpenBankingToolkit/openbanking-directory/pull/116
https://github.com/OpenBankingToolkit/openbanking-common/pull/65
https://github.com/OpenBankingToolkit/openbanking-tpp/pull/151
https://github.com/OpenBankingToolkit/openbanking-analytics/pull/137

**Comment by shprink** [comment]
all Merged

**Comment by shprink** [comment]
e2e test: https://github.com/ForgeCloud/ob-ui-e2e/commit/2f2b241ef0027fae22032745eb20ffa89dfc39d3
